web/framwork3/ldap/app_ldap/urls.py
from django.conf.urls import patterns, url, include

from app_ldap import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^identification/$', views.login_view, name='login_view'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^directory/$', views.directory_view, name='directory_view'),
)

web/framwork3/ldap/ldap_42/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^index/', include('app_ldap.urls', namespace='app_ldap')),
	url(r'^admin/', include(admin.site.urls)),
)

web/framwork3/ldap/app_ldap/models.py
from django.db import models

class User_ldap(models.Model):
	Username = models.CharField(max_length=200)
	Name = models.CharField(max_length=200)
	FirstName = models.CharField(max_length=200)
	Email = models.EmailField()
	Phone = models.IntegerField(default=0)
	Date = models.DateTimeField('date')
	def __str__(self):
		return self.Username

web/framwork3/ldap/app_ldap/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout, login
from django.core.urlresolvers import reverse

from django_auth_ldap.backend import LDAPBackend


def index(request):
	return render(request, "index.html")

def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
			return HttpResponseRedirect(reverse('app_ldap:directory_view'))
	else:
		form = AuthenticationForm()
	return render(request, 'identification.html', {'form' : form})

def logout_view(request):
	logout(request)
	return index(request)

def directory_view(request):
	return render (request, 'directory.html')

web/framwork3/ldap/app_ldap/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>LDAP 42</title>
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}"/>
    </head>
    <body  id="body" >
        <div id="center" >
                {% if user.is_authenticated %}
                    <a href="{% url 'app_ldap:logout_view' %}" ><img id="logout" src="{% static 'logout.png' %}"></a>
                {% else %}
                      <h1>LDAP 42</h1>
                 {% endif %}
            {% block body %}{% endblock %}
        </div>
    </body>
</html>

web/framwork3/ldap/app_ldap/templates/directory.html
{% extends "base.html" %}
{% block body %}

{% endblock %}

web/framwork3/ldap/app_ldap/templates/identification.html
{% extends "base.html" %}
{% block body %}
<div>
	<form method="POST" action="{% url 'app_ldap:login_view' %}">
	{% csrf_token %}
	<fieldset id="fieldset">
	<legend id="legend" >IDENTIFICATION</legend>
		{{form.as_p}}
		<input id="ok" type="submit" value="ENVOYER" name="ok">
	</fieldset>
	</form>
</div>

{% endblock %}

web/framwork3/ldap/app_ldap/templates/index.html
<!-- templates/index.html -->
{% extends "base.html" %}
{% load staticfiles %}
{% block body %}
	{% if user.is_authenticated %}
		<h1 id="h1" >Bienvenue {{ user.username }}</h1>
	{% else %}
		<p class="p" >Bienvenue cliquez <a class="p" href="{% url 'app_ldap:login_view' %}">ici </a> pour vous log</p>
	{% endif %}
{% endblock body %}